---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - ../vars/common.yaml
        - ../vars/rest_connect.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  become: true
  become_user: "{{ webmethods_user }}"
  run_once: true
  vars:
    apigateway_rest_protocol: "{{ vars_rest_protocol }}"
    apigateway_rest_host: "{{ vars_rest_host }}"
    apigateway_rest_port: "{{ vars_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_rest_login_password }}"

  tasks:

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: search_api_ids
        rvar_object_filters:
          - name: "bookstore"
            version: "1.0"
          - name: "uszip"
            version: "1.0"
          - name: "doesnotexist"
            version: "2.0"

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: search_api_ids
        rvar_object_filters:
          - name: "bookstore"
            version: "3.0"
          - name: "uszip"
            version: "1.0"
          - name: "bookstore"
            version: "1.0"