---
_settings_event_destination_common_prefix: "settings_event_destination"
_settings_event_destination_common_enabled: "{{ lookup('env', '%s_configure' | format(_settings_event_destination_common_prefix)) | default('false',true) }}"

## common configs found in many destination payloads
## note: _destination_prefix_item is a dynamic value set by the playbook when merging the dict
_settings_event_destination_common_configs:
      sendAuditlogAPIManagementEvent: "{{ lookup('env', '%s_sendAuditlogAPIManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogAccessProfileManagementEvent: "{{ lookup('env', '%s_sendAuditlogAccessProfileManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogAliasManagementEvent: "{{ lookup('env', '%s_sendAuditlogAliasManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogApplicationManagementEvent: "{{ lookup('env', '%s_sendAuditlogApplicationManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogApprovalManagementEvent: "{{ lookup('env', '%s_sendAuditlogApprovalManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogGroupManagementEvent: "{{ lookup('env', '%s_sendAuditlogGroupManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogPackageManagementEvent: "{{ lookup('env', '%s_sendAuditlogPackageManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogPlanManagementEvent: "{{ lookup('env', '%s_sendAuditlogPlanManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogPolicyManagementEvent: "{{ lookup('env', '%s_sendAuditlogPolicyManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogPromotionManagementEvent: "{{ lookup('env', '%s_sendAuditlogPromotionManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogRuntimeDataManagementEvent: "{{ lookup('env', '%s_sendAuditlogRuntimeDataManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendAuditlogUserManagementEvent: "{{ lookup('env', '%s_sendAuditlogUserManagementEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendErrorEvent: "{{ lookup('env', '%s_sendErrorEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendLifecycleEvent: "{{ lookup('env', '%s_sendLifecycleEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendPerformanceMetrics: "{{ lookup('env', '%s_sendPerformanceMetrics' | format(_destination_prefix_item)) | default('NULL',true) }}"
      sendPolicyViolationEvent: "{{ lookup('env', '%s_sendPolicyViolationEvent' | format(_destination_prefix_item)) | default('NULL',true) }}"
      metricsPublishInterval: "{{ lookup('env', '%s_metricsPublishInterval' | format(_destination_prefix_item)) | default('NULL',true) }}"

## destination elastic search
_settings_event_destination_elastic_type: "elastic"
_settings_event_destination_elastic_prefix: "{{ '%s_%s' | format(_settings_event_destination_common_prefix, _settings_event_destination_elastic_type) }}"
_settings_event_destination_elastic_prefix_item_count: "{{ ansible_env.keys() | map('regex_search', ('^%s.*$' | format( _settings_event_destination_elastic_prefix)) , '\\0') | flatten | select('string') | length }}"
_settings_event_destination_elastic_enabled: "{{ (_settings_event_destination_elastic_prefix_item_count | default('0',true) | int) > 0 }}"
_settings_event_destination_elastic_specific:
      protocol: "{{ lookup('env', '%s_protocol' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
      hostName: "{{ lookup('env', '%s_hostname' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
      port: "{{ lookup('env', '%s_port' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
      userName: "{{ lookup('env', '%s_username' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
      password: "{{ lookup('env', '%s_password' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
      indexName: "{{ lookup('env', '%s_indexName' | format(_settings_event_destination_elastic_prefix)) | default('NULL',true) }}"
_settings_event_destination_elastic_final: "{{ _settings_event_destination_common_configs | combine(_settings_event_destination_elastic_specific) }}"

## destination api portal
_settings_event_destination_apiportal_type: "apiportal"
_settings_event_destination_apiportal_prefix: "{{ '%s_%s' | format(_settings_event_destination_common_prefix, _settings_event_destination_apiportal_type) }}"
_settings_event_destination_apiportal_prefix_item_count: "{{ ansible_env.keys() | map('regex_search', ('^%s.*$' | format( _settings_event_destination_apiportal_prefix)) , '\\0') | flatten | select('string') | length }}"
_settings_event_destination_apiportal_enabled: "{{ (_settings_event_destination_apiportal_prefix_item_count | default('0',true) | int) > 0 }}"
_settings_event_destination_apiportal_specific: {}
_settings_event_destination_apiportal_final: "{{ _settings_event_destination_common_configs | combine(_settings_event_destination_apiportal_specific) }}"