---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_apis.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  tasks:

    - name: activate/deactivate apis
      include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: activate-apis
        configs_enabled: "{{ vars_apis_enabled }}"
        rvar_apigateway_packages: "{{ vars_apis_update_status }}"