---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_event_destinations.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  tasks:

    - name: set prefix item to ensure common attributes are using the right prefix
      set_fact:
         _destination_prefix_item: "{{ _settings_event_destination_elastic_prefix }}"
    
    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _destination_prefix_item
        - _settings_event_destination_elastic_final

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-event-destination
        configs_enabled: "{{ _settings_event_destination_elastic_enabled | default('false',true) }}"
        rvar_apigateway_destination_type: "{{ _settings_event_destination_elastic_type | default('NULL',true) }}"
        rvar_apigateway_destination_config_dict: '{{ _settings_event_destination_elastic_final |
            default({},true) |
            dict2items |
            rejectattr("value", "equalto", "NULL") |
            items2dict }}'

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-event-destination
        configs_enabled: "{{ _settings_event_destination_apiportal_enabled | default('false',true) }}"
        rvar_apigateway_destination_type: "{{ _settings_event_destination_apiportal_type | default('NULL',true) }}"
        rvar_apigateway_destination_config_dict: '{{ _settings_event_destination_apiportal_final |
            default({},true) |
            dict2items |
            rejectattr("value", "equalto", "NULL") |
            items2dict }}'