---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_ssl.yaml

################################################################
## set configs via REST APIs
################################################################

- name: SSL config tasks
  hosts: local
  tasks:

    - include_role:
        name:  apigateway-rest-configurator
      vars:
        configs_action: set-keytruststore-for-connections
        configs_enabled: "{{ vars_ssl_inbound_outbound_enabled }}"
        rvar_apigateway_keytruststore_configuration: "{{ vars_rest_ssl_inbound_outbound_configuration }}"