---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_packages.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  tasks:

    - name: set initial list so it's not undefined
      set_fact:
        _index_items_regex_pattern: "{{ _packages_indices_regex_pattern }}"
        _packages_list: []

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _index_items_regex_pattern
        - _index_items

    - name: append each item to list
      include_tasks: "config_packages_append_each.yaml"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _packages_list

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-packages
        configs_enabled: "{{ vars_packages_enabled }}"
        rvar_apigateway_packages: "{{ _packages_list }}"
