---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_portalgateway.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  vars:
    apigateway_rest_protocol: "{{ vars_rest_protocol }}"
    apigateway_rest_host: "{{ vars_rest_host }}"
    apigateway_rest_port: "{{ vars_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_rest_login_password }}"

  tasks:
    
    ## in this apigateway to apiportal config section, we load the role based on the portaltype
    - debug:
        msg: "WARN - value for vars_portalgateway_portaltype is not defined or empty...will not configure the apiportal connection!"
      when: vars_portalgateway_portaltype is not defined or vars_portalgateway_portaltype == ""

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: Yes
      vars:
        configs_action: set-apiportal-connect
        configs_enabled: "{{ vars_portalgateway_enabled }}"
        webmethods_apigateway_portalgateway: "{{ vars_portalgateway_apiportal }}"
      when: (vars_portalgateway_portaltype | lower) == "apiportal"
      tags:
        - configs_apiportal_connect

    - include_role:
        name: apigateway-rest-configurator
        apply:
          ignore_errors: Yes
      vars:
        configs_action: set-apiportal-connect
        configs_enabled: "{{ vars_portalgateway_enabled }}"
        webmethods_apigateway_portalgateway: "{{ vars_portalgateway_devportal }}"
      when: (vars_portalgateway_portaltype | lower) == "devportal"
      tags:
        - configs_apiportal_connect
