---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/data_plans.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  tasks:

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _index_items_regex_pattern
        - _index_items
    
    - name: set initial list so it's not undefined
      set_fact:
         _plans_list: []

    - name: append each item template to list
      set_fact:
        _plans_list: "{{ _plans_list + [ _plans_template ] }}"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _plans_list

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-plans
        configs_enabled: "{{ vars_plans_enabled }}"
        rvar_apigateway_plans: "{{ _plans_list }}"
