---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_ldap.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  vars:

  tasks:

    - include_role:
        name: apigateway-rest-configurator
      vars:
        configs_action: set-ldap-settings
        configs_enabled: "{{ vars_ldap_enabled }}"
        webmethods_apigateway_ldap_settings: "{{ vars_ldap_settings }}"