---

################################################################
## Load the needed vars
################################################################

- name: Load vars
  hosts: local
  tasks:
    - name: Include all vars files
      include_vars:
        file: "{{ item }}"
      with_fileglob:
        - vars/common.yaml
        - vars/rest_connect.yaml
        - vars/settings_ports.yaml

################################################################
## set configs via REST APIs
################################################################

- hosts: local
  vars:
    apigateway_rest_protocol: "{{ vars_rest_protocol }}"
    apigateway_rest_host: "{{ vars_rest_host }}"
    apigateway_rest_port: "{{ vars_rest_port }}"
    apigateway_rest_no_check_certs: "{{ vars_rest_no_check_certs }}"
    apigateway_rest_login_username: "{{ vars_rest_login_username }}"
    apigateway_rest_login_password: "{{ vars_rest_login_password }}"

  tasks:

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - _index_items_regex_pattern
        - _index_items

    - name: set initial list so it's not undefined
      set_fact:
         _ports_list: []

    - name: append each item to list
      include_tasks: "config_ports_append_each.yaml"
      loop: "{{ _index_items }}"
      loop_control:
        loop_var: index_item

    - ansible.builtin.debug:
        var: _ports_list

    - include_role:
        name:  apigateway-rest-configurator
      vars:
        configs_action: set-ports
        configs_enabled: "{{ vars_ports_enabled }}"
        rvar_apigateway_ports_list: "{{ _ports_list }}"
